site_name: JACoW - IT Documentation
#site_url: https://it-docs.JACoW.org
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: orange
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: orange
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
repo_name: 'jacow-org/docs-it'
repo_url: 'https://github.com/jacow-org/docs-it'
markdown_extensions:
  - admonition
plugins:
  - privacy
  - search
  - open-in-new-tab:
      add_icon: true
nav:
  - Introduction: index.md
  - Networking: networking.md
  - Hardware: hardware.md
  - Software: 
    - Standard Base Software: software/software.md
    - Computer Setup Guides: 
        - Fonts: software/PCsetup/fonts.md
        - Distiller: software/PCsetup/distiller.md
        - Acrobat: software/PCsetup/acrobat.md
        - Adobe PDF printer: software/PCsetup/pdfprinter.md
        - Word 365: software/PCsetup/word365.md
        - PowerPoint 365: software/PCsetup/powerpoint365.md
        - MiKTeX: software/PCsetup/miktex.md
        - Firefox: software/PCsetup/firefox.md
        - PitStop Activation: software/PCsetup/pitstop-activation.md
        - PitStop Configuration: software/PCsetup/pitstop-configuration.md
    - Preparing Multiple Workstations: software/multipleworkstations.md
    - Tools:
      - PDF comparison: software/Tools/PDFcompare.md
  - Backup System: backup.md
  - Space Planning: spaceplanning.md
  - Ergononomics: ergonomics.md
