site_name: JACoW - IT Documentation
#site_url: https://it-docs.JACoW.org
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: orange
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: orange
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
repo_name: 'jacow-org/docs-it'
repo_url: 'https://github.com/jacow-org/docs-it'
markdown_extensions:
  - admonition
plugins:
  - privacy
  - search
  - open-in-new-tab:
      add_icon: true
nav:
  - Introduction: index.md
  - Networking: allthingsit/networking.md
  - Hardware: allthingsit/hardware.md
  - Software: 
    - Standard Base Software: software/software.md
    - Software Requirements: software/requirements.md
    - Preparing Multiple Workstations: software/multipleworkstations.md
    - Tools:
      - PDF comparison: software/Tools/PDFcompare.md
    - Computer Setup Guides: 
        - Fonts: PCsetup/fonts.md
        - Distiller: PCsetup/distiller.md
        - Acrobat: PCsetup/acrobat.md
        - Adobe PDF printer: PCsetup/pdfprinter.md
        - Word 365: PCsetup/word365.md
        - PowerPoint 365: PCsetup/powerpoint365.md
        - MiKTeX: PCsetup/miktex.md
        - Firefox: PCsetup/firefox.md
        - PitStop Activation: PCsetup/pitstop-activation.md
        - PitStop Configuration: PCsetup/pitstop-configuration.md
  - Backup System: allthingsit/backup.md
  - Space Planning: allthingsit/spaceplanning.md
  - Ergononomics: allthingsit/ergonomics.md
